// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"junjiehuang1020.me/go-training-homework/template/internal/demo-app/biz"
	"junjiehuang1020.me/go-training-homework/template/internal/demo-app/data"
	"junjiehuang1020.me/go-training-homework/template/internal/demo-app/service"
)

// Injectors from wire.go:

func InitializeService() *service.UserService {
	db := data.NewDB()
	userRepoImpl := data.NewUserRepoImpl(db)
	userBiz := biz.NewUserBiz(userRepoImpl)
	userService := service.NewUserService(userBiz)
	return userService
}
